### ISSUE TITLE
Duplicate action is not working in Moodle 2.7

### ISSUE THREAD

**Issue by ctam** [at-tools/moodle-block_massaction#12]
In the file [action.php,](https://github.com/at-tools/moodle-block_massaction/blob/master/action.php#L359) it's calling a Moodle function `duplicate_module`, which, I believe, was introduced in Moodle 2.8.  And therefore, it's not working on Moodle 2.7.

**Comment by cdsmith-umn** [comment]
Thank you for the report. I'll take a look and see if there is a way I can get this working in 2.7.

**Comment by cdsmith-umn** [comment]
The only way I could solve this would be to call several functions that do exist in 2.7 in order to perform all the tasks the one in 2.8 and later does. I've pushed a new version for 2.7 and earlier up to Github and will get it up on the Moodle Plugins Directory later this morning. I apologize for any inconvenience.
