### ISSUE TITLE
Problem in Moodle 3.2

### ISSUE THREAD

**Issue by 2shediac** [at-tools/moodle-block_massaction#16]
Hi - trying to use the block in Moodle 3.2 - boost theme.
![mass](https://cloud.githubusercontent.com/assets/16323254/22620114/43a5e798-ead2-11e6-825c-8533111c7b4d.png)

On my sample course - the check boxes to select items are not visible. See attached screen shot. I have tried with different themes - no difference.

Let me know if you need more information.

**Comment by lbroda** [comment]
This is also happening at our site.  
Moodle version: 2016120502.02
 block/massaction version: 2017013100

The following error appears on the console using firebug and may be related:
> TypeError: sections[section_number].modules is undefined           module.js (line 2, col 222)

**Comment by lbroda** [comment]
I'm not a javascript wizard, but the problem seems to be in referencing a non-existent property, and at our site, this patch fixed it:

diff -rbBc a/blocks/massaction/js/module_selector.js b/blocks/massaction/js/module_selector.js
*** a/blocks/massaction/js/module_selector.js	2017-04-26 08:43:19.366344154 -0500
--- b/blocks/massaction/js/module_selector.js	2017-04-26 08:50:20.030724809 -0500
***************
*** 101,106 ****
--- 101,108 ----
      } else {
          // Add the section to the registry.
          self.sections[section_number] = [];
+        // Initialize modules property.
+         self.sections[section_number].modules = [];
          
          // Find all LI with class 'activity' or 'resource'.
          LIs = Y.one('#section-' + section_number).all('li.activity');

**Comment by lbroda** [comment]
This patch has fixed the problem at our site (it seemed to result from attempts to add values to a non-existent property)
[massaction_patch.txt](https://github.com/at-tools/moodle-block_massaction/files/958642/massaction_patch.txt)

**Comment by cdsmith-umn** [comment]
I apologize for the delay in getting this fixed. I didn't have my watch settings correct. That should also now be corrected.
