### ISSUE TITLE
Massaction plus Onetopic format

### ISSUE THREAD

**Issue by heathgmonash** [at-tools/moodle-block_massaction#21]
When Mass Action is used with Onetopic format, and Section 0 is set to display above the tabs, Mass Action will only work in Section 0. If Section 0 is set to display as a tab, it works as expected. 

![image](https://user-images.githubusercontent.com/33848417/33045933-e268b504-cea2-11e7-8f3e-319bc61ad7d6.png)

**Comment by cdsmith-umn** [comment]
Hmm. I did not realize that was a choice with the OneTopic format. I'll have a look at this as soon as I'm able.

**Comment by cdsmith-umn** [comment]
@heathgmonash I need some help reproducing the problem. Could you give me instructions on how to reproduce the problem you've encountered? I ask because I have been able to perform all actions available through the block on activities displayed on the page, as well as on activities that are in a topic that is not currently selected (i.e., you're looking at Topic 1 and Topic 1's activities are displayed on the page, and I moved/duplicated/deleted/outdented/indented/hid/showed activities for Topic 6 while looking at Topic 1).

**Comment by cdsmith-umn** [comment]
Closing since there has been no response in five months.
